### ISSUE TITLE
Validacion de la carga de parametros de distribucion.

### ISSUE THREAD

**Issue by GonzaloSaad** [GonzaloSaad/sim-tp-3-2018#4]
Cada distribucion tiene sus parametros.

Uniforme -> `{a,b}`
Normal -> `{mu, sigma}`
Exponencial -> `{lambda}`

Hay que averiguar que restricciones tienen cada uno de los parametros, por ejemplo, (b no puede ser menor que a).

**Comment by Codes97** [comment]
Yo estoy haciendo esta (asi no nos pisamos)

**Comment by GonzaloSaad** [comment]
Acepta la solicitud de colaboracion asi podes pushear

**Comment by GonzaloSaad** [comment]
Uniforme -> a menor que b.
Exponencial -> Lambda no negativo.
Normal ->sigma no negativo.

**Comment by GonzaloSaad** [comment]
Hubo una validacion que salio mal me parece. 

![image](https://user-images.githubusercontent.com/32211561/45005579-dc062180-afb9-11e8-8e1a-a5573516207e.png)

@Codes97 @ignaciocaff
