### ISSUE TITLE
Tipo de dato ingresado en spinner de double.

### ISSUE THREAD

**Issue by GonzaloSaad** [GonzaloSaad/sim-tp-3-2018#6]
Cuando se ingresa un caracter especial o no permitido en los spinners de tipo double, revienta. 

Lo mas probable es que en la validacion de textbox de cada spineer se pueda poner un match de Double y si no concuerda, restartear.

**Comment by GonzaloSaad** [comment]
Textbox = textfield en java fx

**Comment by Codes97** [comment]
Esto lo soluciono alguien? Yo no subi nada y ya esta arreglado..

**Comment by GonzaloSaad** [comment]
No esta arreglado, no se pueden usar los spiners de double. Acabo de verificar. No lo de usar las flechitas, sino la accion de editarlo.

**Comment by Codes97** [comment]
Yo ya habia intentado hacer una validacion como la que hiciste pero resulta incomodo a la hora de escribir. Por eso pensaba hacer la validacion a la hora de tocar el generar

**Comment by GonzaloSaad** [comment]
Creo que la mejor seria dejar un textfield solo, y como decis vos, hacer la validacion al generar. Es decir sacar el spinner de double para los parametros a, b, mu, sigma y lambda.

**Comment by ignaciocaff** [comment]
Estoy por subir al branch de Santi esto que me pidió que lo haga hoy. Fijense que les parece, borre bastante código que no utilizaba al pasar a TextField. Esta completo en teoría, la única validación que no hice porque no encontre bien la formula, es en EXP.NEG hay una relación entre Lambda y Alpha, que en determinado punto salta una excepcion de la librería.

**Comment by GonzaloSaad** [comment]
Ah de una, si la vi a la exception, en realidad por lo que pude experimentar, es cuando el lambda es muy muy chico.
